fragment RecordHolderFields on RecordHistoryEntry {
    levelPosition
    time
    levelDecayedPoints
    userSteamId
    userName
    playerDecayedPoints
}

subscription WatchCurrentLevelRecords($xxHash: String!, $steamId: BigInt!) {
    query {
        personalBest: recordHistoryEntries(
            filter: {
                historyView: { equalTo: "personal-bests" }
                levelXxHash: { equalTo: $xxHash }
                userSteamId: { equalTo: $steamId }
            }
            first: 1
        ) {
            nodes {
                ...RecordHolderFields
            }
        }
        worldRecord: recordHistoryEntries(
            filter: {
                historyView: { equalTo: "world-records" }
                levelXxHash: { equalTo: $xxHash }
            }
            first: 1
        ) {
            nodes {
                ...RecordHolderFields
            }
        }
    }
}
