fragment CurrentLevelRecordFields on Query {
    personalBest: records(
        first: 1
        filter: {
            personalBestGlobalsExist: true
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
            user: { steamId: { equalTo: $steamId } }
        }
        orderBy: [TIME_ASC, DATE_CREATED_ASC]
    ) {
        nodes {
            id
            time
            dateCreated
            userPointContributions(first: 1) {
                nodes {
                    levelPosition
                    levelDecayedPoints
                }
            }
        }
    }
    worldRecord: records(
        first: 1
        filter: {
            worldRecordGlobalsExist: true
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
        }
        orderBy: [TIME_ASC, DATE_CREATED_ASC]
    ) {
        nodes {
            id
            time
            user {
                steamId
                steamName
            }
        }
    }
}

subscription WatchCurrentLevelRecords($xxHash: String!, $hash: String!, $steamId: BigInt!) {
    query {
        ...CurrentLevelRecordFields
    }
}
