fragment LeaderboardPageFields on Query {
    levelItems(
        first: 1
        filter: {
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
        }
    ) {
        nodes {
            name
        }
    }
    levelPoints(
        first: 1
        filter: {
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
        }
    ) {
        nodes {
            points
        }
    }
    records(
        filter: {
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
            personalBestGlobalsExist: true
        }
        first: $first
        offset: $offset
        orderBy: TIME_ASC
    ) {
        totalCount
        nodes {
            user {
                steamName
                steamId
            }
            time
            dateCreated
        }
    }
}

query LeaderboardPage($xxHash: String!, $hash: String!, $first: Int!, $offset: Int!) {
    levelItems(
        first: 1
        filter: {
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
        }
    ) {
        nodes {
            name
        }
    }
    levelPoints(
        first: 1
        filter: {
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
        }
    ) {
        nodes {
            points
        }
    }
    records(
        filter: {
            level: {
                or: [
                    { xxHash: { equalTo: $xxHash } }
                    {
                        and: [
                            { hash: { equalTo: $hash } }
                            { adventure: { equalTo: true } }
                        ]
                    }
                ]
            }
            personalBestGlobalsExist: true
        }
        first: $first
        offset: $offset
        orderBy: TIME_ASC
    ) {
        totalCount
        nodes {
            user {
                steamName
                steamId
            }
            time
            dateCreated
        }
    }
}

subscription WatchLeaderboardPage($xxHash: String!, $hash: String!, $first: Int!, $offset: Int!) {
    query {
        ...LeaderboardPageFields
    }
}
